### ISSUE TITLE
 split profiles based on pressure

### ISSUE THREAD

**Issue by jmunroe** [oceanhackweek/ohw20-proj-ooi-profiles-section#13]

**Comment by jmunroe** [comment]
@kmcgarry17: How long (minutes / hours?) does an up versus downcast take?

**Comment by jmunroe** [comment]
How is this being done here:  https://nbviewer.jupyter.org/gist/ocefpaf/f1cf8fc7ad18557d49944fd6385d3c9a (Filipe's gist)... needs further explanation

**Comment by sbeaulieu** [comment]
Completed
