### ISSUE TITLE
Interpolate across distance

### ISSUE THREAD

**Issue by jmunroe** [oceanhackweek/ohw20-proj-ooi-profiles-section#14]
Looking at Filipe gist

**Comment by ocefpaf** [comment]
Which one?

**Comment by jmunroe** [comment]
Ha! We are using "Filipe's gist" as specific reference to something we linked in the Wiki.   In this case: https://nbviewer.jupyter.org/gist/ocefpaf/f1cf8fc7ad18557d49944fd6385d3c9a

**Comment by jmunroe** [comment]
Progress on this from #16
