### ISSUE TITLE
Remove/merge "loadOOI_KM.ipynb"  and "oneday_multprofilersKM.ipynb" ?

### ISSUE THREAD

**Issue by jmunroe** [oceanhackweek/ohw20-proj-ooi-profiles-section#25]
@kmcgarry17  Is there anything in `loadOOI_KM.ipynb` that needs to be moved over to 01_OOI_Profiles.ipynb ?

**Comment by jmunroe** [comment]
Also, is there anything different in `oneday_multprofilersKM.ipynb` that should be merged in?

**Comment by jmunroe** [comment]
@sbeaulieu says "yes". The figure showing the profiles needs to be kept.

**Comment by sbeaulieu** [comment]
Completed
