### ISSUE TITLE
Create a shared environment.yml file

### ISSUE THREAD

**Issue by jmunroe** [oceanhackweek/ohw20-proj-ooi-profiles-section#6]
We need a conda environment.yml file that lists the packages (like netCDF4 and cmocean) that we need to run these notebooks.  

Also, we should add instructions to the README.md on how to set up this environment.

**Comment by svenja-ryan** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by sryan288** [comment]
I created a yml file will upload and create pull request

**Comment by jmunroe** [comment]
Thanks.  I don't think we need all of the "R" packages in there.  Also, a standard name for these kind of files is `environment.yml`. Could you make that change too?

**Comment by jmunroe** [comment]
Also, when you submit your PR, you can associate it with this issue.  Alternatively, in your commit message you include #6 and I think the association will automatically be linked.

**Comment by jmunroe** [comment]
Moreover, looking more closely at your environment yml, you have very specific versions.  Maybe something closer to how the original OHW20 environment was written? https://github.com/oceanhackweek/ohw20-tutorials/blob/master/environment.yml

**Comment by svenja-ryan** [comment]
I'll try to get rid of all the R packages and rename the fill. Will also try to incorporate the issue in the pull request - that makes it much neater of course.

I thought I used the original ohw environment.yml and only added cmocean. Can't recall using specific versions but I'll also look into that - thanks for noticing!

**Comment by jmunroe** [comment]
Awesome, thanks!
