### ISSUE TITLE
Adopt script/notebook to access and plot OOI Pioneer profiler mooring CTD profile data

### ISSUE THREAD

**Issue by jmunroe** [oceanhackweek/ohw20-proj-ooi-profiles-section#8]

**Comment by jmunroe** [comment]
@sbeaulieu :  I would like to plot the same day’s salinity vs pressure data for all 4 moorings (e.g., a 4-panel figure). Note Svenja’s notebook comments re: time; I think Sage does a work-around by using pandas data frames. Asked OOI Data Manager re: downcast/upcast

**Comment by sbeaulieu** [comment]
We now have a couple of notebooks that plot CTD data from all 4 profiler moorings
